# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=256, verbose_name='Назва предмету')),
                ('date', models.DateField(verbose_name='Дата проведення')),
                ('teacher_name', models.CharField(max_length=256, verbose_name='Викладач')),
                ('notes', models.TextField(blank=True, verbose_name='Додаткові нотатки')),
                ('exam_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Group', verbose_name='Група')),
            ],
            options={
                'verbose_name': 'Екзамен',
                'verbose_name_plural': 'Екзамени',
            },
        ),
    ]
